- name: Copy Dockerfile
  copy:
    src: ../files/Dockerfile
    dest: "{{app_folder}}/Dockerfile"

- name: Docker registry login
  docker_login:
    username: "{{docker_user}}"
    password: "{{docker_pass}}"
    email: "{{docker_email}}"

# - name: Build and push image
#   docker_image:
#     build:
#       path: "{{app_folder}}"
#     name: myapp
#     repository: "{{docker_repo}}"
#     tag: "{{tag}}"
#     push: yes
#     source: build
#     force: yes

# fatal: [84.201.157.213]: FAILED! => {"changed": false, "msg": "Error building enfuras/myapp - code: None, message: COPY failed: stat /var/lib/docker/tmp/docker-builder153211564/user-registration-application-0.0.1-SNAPSHOT.war: no such file or directory, logs: [u'Step 1/2 : FROM tomcat:8.5-alpine', u'\\n', u' ---> 8b8b1eb786b5\\n', u'Step 2/2 : COPY user-registration-application-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/', u'\\n']"}

- name: docker build
  shell: "docker build -t {{image}}:{{tag}} ."
  args:
    chdir: "{{app_folder}}"

- name: Build and push image
  docker_image:
      path: "{{app_folder}}"
      name: "{{docker_user}}/{{image}}"
      tag: "{{tag}}"
      push: yes