- name: Ensure all packages is installed
  apt:
    name: "{{item}}"
    state: present
  with_items: "{{packages}}"
  when: ansible_os_family == "Debian"

- name: Ensure all packages is installed
  yum:
    name: "{{item}}"
    state: present
  with_items: "{{packages}}"
  when: ansible_os_family == "Redhat"

- name: Ensure folder for application exists
  file:
    name: "{{app_folder}}"
    state: directory
    recurse: yes