---
# tasks file for web
- name: Docker registry login
  docker_login:
    username: "{{docker_user}}"
    password: "{{docker_pass}}"
    email: "{{docker_email}}"

- name: Run application
  docker_container:
    name: 
    image: "{{docker_user}}/{{image}}:{{tag}}"
    state: started
    pull: true
    restart: yes
    ports:
      - "{{host_port}}:{{app_port}}"